-- Privacy-conscious product analytics for the Ralli participation funnel.
-- Events contain identifiers and controlled context only, never captions, media,
-- wallet addresses, invitation tokens, or other user-authored content.

create table public.product_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id uuid not null,
  event_name text not null check (event_name in (
    'app_opened',
    'ralli_opened',
    'response_started',
    'response_published',
    'responses_viewed',
    'invitation_shared',
    'invitation_opened',
    'invitation_accepted',
    'community_opened',
    'community_joined'
  )),
  source text check (source is null or char_length(source) <= 40),
  ralli_id uuid references public.rallis(id) on delete set null,
  response_id uuid references public.responses(id) on delete set null,
  community_id uuid references public.communities(id) on delete set null,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint product_event_properties_are_object check (jsonb_typeof(properties) = 'object'),
  constraint product_event_properties_size check (pg_column_size(properties) <= 2048)
);

create index product_events_name_created_idx on public.product_events(event_name, created_at desc);
create index product_events_user_created_idx on public.product_events(user_id, created_at desc);
create index product_events_ralli_created_idx on public.product_events(ralli_id, created_at desc) where ralli_id is not null;

alter table public.product_events enable row level security;

create policy "Users record their own product events"
  on public.product_events for insert to authenticated
  with check (user_id = (select auth.uid()));

grant insert on public.product_events to authenticated;
grant usage, select on sequence public.product_events_id_seq to authenticated;

-- Aggregated dashboard data is intentionally unavailable to app clients.
create view public.product_funnel_daily
with (security_invoker = true)
as
select
  created_at::date as event_date,
  event_name,
  source,
  count(*)::bigint as events,
  count(distinct user_id)::bigint as users
from public.product_events
group by created_at::date, event_name, source;

create view public.product_funnel_30d
with (security_invoker = true)
as
with user_funnel as (
  select
    user_id,
    count(distinct created_at::date) as active_days,
    bool_or(event_name = 'ralli_opened') as opened_ralli,
    bool_or(event_name = 'response_started') as started_response,
    bool_or(event_name = 'response_published') as published_response,
    bool_or(event_name = 'responses_viewed') as viewed_responses,
    bool_or(event_name = 'invitation_shared') as shared_invitation,
    bool_or(event_name = 'invitation_opened') as opened_invitation,
    bool_or(event_name = 'invitation_accepted') as accepted_invitation,
    bool_or(event_name = 'community_joined') as joined_community
  from public.product_events
  where created_at >= now() - interval '30 days'
  group by user_id
)
select
  count(*)::bigint as active_users,
  count(*) filter (where active_days >= 2)::bigint as returning_users,
  count(*) filter (where opened_ralli)::bigint as ralli_openers,
  count(*) filter (where started_response)::bigint as response_starters,
  count(*) filter (where published_response)::bigint as response_publishers,
  count(*) filter (where viewed_responses)::bigint as response_viewers,
  count(*) filter (where shared_invitation)::bigint as invitation_senders,
  count(*) filter (where opened_invitation)::bigint as invitation_openers,
  count(*) filter (where accepted_invitation)::bigint as invitation_accepters,
  count(*) filter (where joined_community)::bigint as community_joiners,
  round(100.0 * count(*) filter (where published_response) / nullif(count(*) filter (where started_response), 0), 1) as start_to_publish_percent,
  round(100.0 * count(*) filter (where viewed_responses) / nullif(count(*) filter (where published_response), 0), 1) as publish_to_view_percent,
  round(100.0 * count(*) filter (where accepted_invitation) / nullif(count(*) filter (where opened_invitation), 0), 1) as invitation_accept_percent,
  round(100.0 * count(*) filter (where active_days >= 2) / nullif(count(*), 0), 1) as returning_user_percent
from user_funnel;

revoke all on public.product_funnel_daily, public.product_funnel_30d from anon, authenticated;
grant select on public.product_events, public.product_funnel_daily, public.product_funnel_30d to service_role;
